### ISSUE TITLE
Request addition: 5.14 supports prototype +

### ISSUE THREAD

**Issue by cxw42** [choroba/syntactic-construct#28]
Thank you for this tool!  Per [perl5140delta](https://perldoc.perl.org/perl5140delta.html#Single-term-prototype), `+` is a valid character in prototypes beginning with 5.14.  I do not see that listed in S::C.  Would you please add it?  Thank you for considering this request!

**Comment by choroba** [comment]
Good catch!

**Comment by choroba** [comment]
Fixed in 531a9b67d5bc6219e3ba6c6e4ca3e57aa9e46910
