### ISSUE TITLE
Add ?> and (?*atomic:...) regex group?  (5.005, 5.028)

### ISSUE THREAD

**Issue by cxw42** [choroba/syntactic-construct#30]
Are pre-5.006 constructs in scope of this pragma?  '?>' was added in 5.005 per [perl5005delta](https://metacpan.org/pod/distribution/perl/pod/perl5005delta.pod#New-regular-expression-constructs).

The longer version, `(?*atomic)`, is experimental in 5.28+ per [perlreref 5.28.0](https://perldoc.pl/5.28.0/perlreref).  However, I can't find it in `feature` or `experimental`.  That makes me think it may be in scope for S::C.

**Comment by choroba** [comment]
This module doesn't support pre-5.6 perls. It's already almost impossible to test 5.6 on travis etc.
The `(?*plb:` at al.  are documented in `perlretut`, `perlreref`, and `perlre`. Using them requires `no warnings 'experimental::alpha_assertions'`, so `Syntax::Construct` is not needed.

**Comment by choroba** [comment]
In fact, `feature` and `experimental` are different to `warnings::experimental`. To confuse us even more, there's also `perlexperiment`.

**Comment by cxw42** [comment]
Yesterday I saw an update to List::AllUtils - maybe I should write Syntax::AllTheVersionSpecificThings as a similar umbrella module for feature/experimental/S::C/... :) .  (Or a pragma `whatever_I_need_for` ;) .) 
 Anyway, thanks for the explanation and pointers!
