### ISSUE TITLE
Automatically `feature->import::into`?

### ISSUE THREAD

**Issue by cxw42** [choroba/syntactic-construct#31]
In S::C 1.014, `use Syntax::Construct '//';` will throw if I'm not running under 5.010+.  However, it will not enable the 5.010 features as `use v5.010;` would.  Example:

    $ perl -MSyntax::Construct=// -e 'say 1//2'
    Number found where operator expected at -e line 1, near "say 1"
            (Do you need to predeclare say?)
    syntax error at -e line 1, near "say 1"
    Execution of -e aborted due to compilation errors.

I would like to request an option (or standard behaviour?) that would cause S::C to import `feature` for the minimum required version.  E.g., specifying `//` would cause `import()` to do `feature->import::into(caller, ':5.10')`.  Then I would not have to separately `use v5.NNN` --- the `use S::C` line would take care of it for me.  E.g., automatically do the `-Mfeature` in:

    $ perl -MSyntax::Construct=// -Mfeature=:5.10 -e 'say 1//2'
    1

If this option already exists and I am missing it somehow, would you please point me in the right direction?  I don't see it in the S::C source.

Thank you for considering this request!

**Comment by choroba** [comment]
I understand where this is coming from, but I fear it hasn't been implemented for a reason: this module exists to make things *explicit*. Implicitly enabling features goes against its main raison d'être. I personally prefer `use feature qw{ say }` to `use 5.10` (or even `use 5.24` to only summon `say`). In throw-away one-liners, we can use `-E`, but in modules and programs, explicitly listing the required features and constructs is what helps users the most.

**Comment by cxw42** [comment]
@choroba Fair enough --- sounds like we have different use cases.  I am trying to document, but am also trying to reduce module boilerplate.  Plus, I worry about my `use 5.xxx` getting out of sync with my `use S::C`. :)

Would you be open to a PR adding a separate module to this dist?  The new module would forward `import()` args to S::C, and then do `feature->import::into`.  Some candidate names I can think of for such a module are S::C::Activate, S::C::Use, Perl::Having (i.e., use the Perl version having the syntax features `qw(...)`), and Perl::With.

**Comment by choroba** [comment]
A new module doesn't sound bad. Do you see any problems with not making it part of the same distribution?

**Comment by cxw42** [comment]
Nope - I'll roll a new dist.  Thanks for following up!
