### ISSUE TITLE
5.025 changed return value of a hash in scalar context

### ISSUE THREAD

**Issue by djerius** [choroba/syntactic-construct#47]
Not sure if this fits into the spirit of what's being tracked. From [perldata](https://perldoc.pl/perldata#Scalar-values)

> If you evaluate a hash in scalar context, it returns a false value if the hash is empty. If there are any key/value pairs, it returns a true value. A more precise definition is version dependent.
>
> Prior to Perl 5.25 the value returned was a string consisting of the number of used buckets and the number of allocated buckets, separated by a slash.

**Comment by choroba** [comment]
It probably does, thanks.

**Comment by choroba** [comment]
Fixed in 59c9666215daec51ca453c652a44f886802c4f1a.
